spring:
  cloud:
    gateway:
      routes:
      - id: serv-vuelos
        #lb: // cuando se va a acceder a traves de eureka
        uri: lb://servicio-vuelos
        predicates:
        - Path=/svuelos/**
        filters:
        -  RewritePath=/svuelos/*, /
        
      - id: serv-hoteles
        uri: lb://servicio-hoteles
        predicates:
        -  Path= /shoteles/**
        filters:
        - RewritePath= /shoteles/*, /
        
      - id: servicio-reserva
        uri: lb://servicio-reserva
        predicates:
        - Path= /sreservas/**
        filters:
        - RewritePath=/sreservas/*, /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7000
          
